
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emeka
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    
    Question Quizz1 = new Question("Repond a ma question","je 1suis", "je ne suis pas","je suis la","je pars", 1);
    Question Quizz2 = new Question("Repond a ma question2","je 2suis", "je ne suis pas","je suis la","je pars", 2);
    Question Quizz3 = new Question("Repond a ma question3","je 3suis", "je ne suis pas","je suis la","je pars", 3);
    Question Quizz4 = new Question("Repond a ma question4","je 4suis", "je ne suis pas","je suis la","je pars", 4);
    Question Quizz5 = new Question("Repond a ma question5","je 5suis", "je ne suis pas","je suis la","je pars", 1);
    private int compteur = 0 ;
    private int score = 0 ;
    ArrayList<Question> tab = new ArrayList<Question>();
    /**
     * Creates new form FenetreQuiz
     */
    public Question questionsuivante(int nombre){
        return tab.get(nombre);
    }
    
    public FenetreQuiz() {
        initComponents();
        tab.add(Quizz1);
        tab.add(Quizz2);
        tab.add(Quizz3);
        tab.add(Quizz4);
        tab.add(Quizz5);
        Question question = tab.get(0);
        
       
        Q1.setText(question.getQ1());
        Q2.setText(question.getQ2());
        Q3.setText(question.getQ3());
        Q4.setText(question.getQ4());
        Consigne.setText(question.getInti());
        Suite.setVisible(false);
        Q1.setVisible(false);
        Q2.setVisible(false);
        Q3.setVisible(false);
        Q4.setVisible(false);
        Consigne.setVisible(false);
        Resultat.setVisible(false); 
        B1.setVisible(false);
        B2.setVisible(false);
        B3.setVisible(false);
        B4.setVisible(false);
        Score.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Consigne = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        Q3 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Q4 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        Resultat = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        Start = new javax.swing.JButton();
        Suite = new javax.swing.JButton();
        Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Consigne.setText("jLabel1");

        Q1.setText("jLabel1");

        Q3.setText("jLabel2");

        Q2.setText("jLabel3");

        Q4.setText("jLabel4");

        B1.setText("Bouton 1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        Resultat.setText("Resultat");

        B2.setText("Bouton 2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setText("Bouton 3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setText("Bouton 4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Suite.setText("Suivant");
        Suite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuiteActionPerformed(evt);
            }
        });

        Score.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B3)
                                    .addComponent(B1))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B2))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Start))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Suite))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Consigne, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Q4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(Q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Consigne)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1)
                    .addComponent(Q2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(B2)
                    .addComponent(Resultat))
                .addGap(18, 18, 18)
                .addComponent(Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Q3)
                            .addComponent(Q4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B3)
                    .addComponent(B4))
                .addGap(8, 8, 8)
                .addComponent(Suite))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        Question H = tab.get(compteur);
        int rep= H.reponse();
        if (rep == 1){
            score+=1;
            Resultat.setText("Bonne reponse");
        }
        else{
            Resultat.setText("Mauvaise reponse");
            
        }
        B1.setEnabled(false);
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(false);
        Resultat.setVisible(true);
        
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        Question H = tab.get(compteur);
        int rep= H.reponse();
        
        if (rep == 2){
            score+=1;
            Resultat.setText("Bonne reponse");
        }
        else{
            Resultat.setText("Mauvaise reponse");
            
        }
        B1.setEnabled(false);
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(false);
        Resultat.setVisible(true);
      
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        Question H = tab.get(compteur);
        int rep= H.reponse();
        if (rep == 3){
            score+=1;
            Resultat.setText("Bonne reponse");
        }
        else{
            Resultat.setText("Mauvaise reponse");
            
        }
        B1.setEnabled(false);
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(false);
        Resultat.setVisible(true);
        
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        Question H = tab.get(compteur);
        int rep= H.reponse();
        if (rep == 4){
            score+=1;
            Resultat.setText("Bonne reponse");
        }
        else{
            Resultat.setText("Mauvaise reponse");
            
        }
        B1.setEnabled(false);
        B2.setEnabled(false);
        B3.setEnabled(false);
        B4.setEnabled(false);
        Resultat.setVisible(true);
        
    }//GEN-LAST:event_B4ActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        
        Q1.setVisible(true);
        Q2.setVisible(true);
        Q3.setVisible(true);
        Q4.setVisible(true);
        B1.setVisible(true);
        B2.setVisible(true);
        B3.setVisible(true);
        B4.setVisible(true);
        Consigne.setVisible(true);
        Start.setVisible(false);
        Suite.setVisible(true);
    }//GEN-LAST:event_StartActionPerformed

    private void SuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuiteActionPerformed
        
        compteur+=1;
        if (compteur<tab.size()){
        Question Qsuivante = questionsuivante(compteur);
        Q1.setText(Qsuivante.getQ1());
        Q2.setText(Qsuivante.getQ2());
        Q3.setText(Qsuivante.getQ3());
        Q4.setText(Qsuivante.getQ4());
        Consigne.setText(Qsuivante.getInti());
        Q1.setVisible(true);
        Q2.setVisible(true);
        Q3.setVisible(true);
        Q4.setVisible(true);
        B1.setVisible(true);
        B2.setVisible(true);
        B3.setVisible(true);
        B4.setVisible(true);
        Consigne.setVisible(true);
        Start.setVisible(false);
        B1.setEnabled(true);
        B2.setEnabled(true);
        B3.setEnabled(true);
        B4.setEnabled(true);}
        else{
            Score.setText("le score est de " + score);
            Score.setVisible(true);
            Q1.setVisible(false);
        Q2.setVisible(false);
        Q3.setVisible(false);
        Q4.setVisible(false);
        B1.setVisible(false);
        B2.setVisible(false);
        B3.setVisible(false);
        B4.setVisible(false);
        Consigne.setVisible(false);
        Suite.setVisible(false);
        Resultat.setVisible(false);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_SuiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JLabel Consigne;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Resultat;
    private javax.swing.JLabel Score;
    private javax.swing.JButton Start;
    private javax.swing.JButton Suite;
    // End of variables declaration//GEN-END:variables
}
