/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emeka
 */
public class ecran_start extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ecran_start.class.getName());

    /**
     * Creates new form ecran_start
     */
    public ecran_start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titre_accueil = new javax.swing.JLabel();
        bt_start = new javax.swing.JButton();
        bt_leave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titre_accueil.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Titre_accueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titre_accueil.setText("Bienvenue  sur Cadenas");
        Titre_accueil.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(Titre_accueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 400, -1));

        bt_start.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_start.setText("Start");
        bt_start.setBorder(new javax.swing.border.MatteBorder(null));
        bt_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_startActionPerformed(evt);
            }
        });
        getContentPane().add(bt_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 106, 104, 36));

        bt_leave.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        bt_leave.setText("Leave");
        bt_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_leaveActionPerformed(evt);
            }
        });
        getContentPane().add(bt_leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_startActionPerformed
        Interface I = new Interface();
        I.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_startActionPerformed

    private void bt_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_leaveActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_leaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ecran_start().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titre_accueil;
    private javax.swing.JButton bt_leave;
    private javax.swing.JButton bt_start;
    // End of variables declaration//GEN-END:variables
}
