/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emeka
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());
    // objet Cadenas Test
    Cadenas Combinaison_now = new Cadenas(0,0,0,0);
    int nb_tentative;
    
    /**
     * Creates new form Interface
     * @param nb_tentative
     */
    public Interface(int nb_tentative) {
        this.nb_tentative= nb_tentative;
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nb_chiffre_case_1 = new javax.swing.JLabel();
        nb_chiffre_case_2 = new javax.swing.JLabel();
        nb_chiffre_case_3 = new javax.swing.JLabel();
        nb_chiffre_case_4 = new javax.swing.JLabel();
        bt_down_1 = new javax.swing.JButton();
        bt_down_2 = new javax.swing.JButton();
        bt_down_3 = new javax.swing.JButton();
        bt_down_4 = new javax.swing.JButton();
        bt_up_1 = new javax.swing.JButton();
        bt_up_2 = new javax.swing.JButton();
        bt_up_3 = new javax.swing.JButton();
        bt_up_4 = new javax.swing.JButton();
        bt_test = new javax.swing.JButton();
        txt_chiffre_trop_bas = new javax.swing.JLabel();
        txt_chiffre_exacts = new javax.swing.JLabel();
        txt_chiffre_trop_hauts = new javax.swing.JLabel();
        nb_chiffre_trop_bas = new javax.swing.JLabel();
        nb_chiffre_exacts = new javax.swing.JLabel();
        nb_chiffre_trop_hauts = new javax.swing.JLabel();
        bt_restart = new javax.swing.JButton();
        txt_tentative = new javax.swing.JLabel();
        nb_score = new javax.swing.JLabel();
        txt_encouragement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nb_chiffre_case_1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        nb_chiffre_case_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nb_chiffre_case_1.setText("0");
        getContentPane().add(nb_chiffre_case_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 80));

        nb_chiffre_case_2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        nb_chiffre_case_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nb_chiffre_case_2.setText("0");
        getContentPane().add(nb_chiffre_case_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 80));

        nb_chiffre_case_3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        nb_chiffre_case_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nb_chiffre_case_3.setText("0");
        getContentPane().add(nb_chiffre_case_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 80, 80));

        nb_chiffre_case_4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        nb_chiffre_case_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nb_chiffre_case_4.setText("0");
        getContentPane().add(nb_chiffre_case_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 80, 80));

        bt_down_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_down_1.setText("DOWN");
        bt_down_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 20));

        bt_down_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_down_2.setText("DOWN");
        bt_down_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, 20));

        bt_down_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_down_3.setText("DOWN");
        bt_down_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, 20));

        bt_down_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_down_4.setText("DOWN");
        bt_down_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_down_4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_down_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, 20));

        bt_up_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_up_1.setText("UP");
        bt_up_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        bt_up_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_up_2.setText("UP");
        bt_up_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 80, 20));

        bt_up_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_up_3.setText("UP");
        bt_up_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 80, 20));

        bt_up_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_up_4.setText("UP");
        bt_up_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_up_4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt_up_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 20));

        bt_test.setText("Tester");
        bt_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_testActionPerformed(evt);
            }
        });
        getContentPane().add(bt_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        txt_chiffre_trop_bas.setText("Nombre de chiffres trop bas : ");
        getContentPane().add(txt_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        txt_chiffre_exacts.setText("Nombre de chiffres exacts : ");
        getContentPane().add(txt_chiffre_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, -1));

        txt_chiffre_trop_hauts.setText("Nombre de chiffres trop hauts  : ");
        getContentPane().add(txt_chiffre_trop_hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, -1));

        nb_chiffre_trop_bas.setText("0");
        nb_chiffre_trop_bas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 30, 30));

        nb_chiffre_exacts.setText("0");
        nb_chiffre_exacts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nb_chiffre_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 30, 30));

        nb_chiffre_trop_hauts.setText("0");
        nb_chiffre_trop_hauts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nb_chiffre_trop_hauts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 30, 30));

        bt_restart.setText("Recommencer");
        bt_restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_restartActionPerformed(evt);
            }
        });
        getContentPane().add(bt_restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        txt_tentative.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_tentative.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tentative.setText("TENTATIVE");
        getContentPane().add(txt_tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 80, -1));

        nb_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nb_score.setText("0 sur 10");
        nb_score.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(nb_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, 30));

        txt_encouragement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_encouragement.setText("Vous avez 10 tentatives. Bonne Mission !");
        getContentPane().add(txt_encouragement, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 10, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_up_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_1ActionPerformed
        Combinaison_now.upval_case(0);
        nb_chiffre_case_1.setText(Combinaison_now.getval_case(0) + "");
       
    }//GEN-LAST:event_bt_up_1ActionPerformed

    private void bt_down_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_1ActionPerformed
        Combinaison_now.downval_case(0);
        nb_chiffre_case_1.setText(Combinaison_now.getval_case(0) + "");
    }//GEN-LAST:event_bt_down_1ActionPerformed

    private void bt_down_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_2ActionPerformed
        Combinaison_now.downval_case(1);
        nb_chiffre_case_2.setText(Combinaison_now.getval_case(1) + "");
    }//GEN-LAST:event_bt_down_2ActionPerformed

    private void bt_down_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_3ActionPerformed
       Combinaison_now.downval_case(2);
        nb_chiffre_case_3.setText(Combinaison_now.getval_case(2) + "");
    }//GEN-LAST:event_bt_down_3ActionPerformed

    private void bt_down_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_down_4ActionPerformed
        Combinaison_now.downval_case(3);
        nb_chiffre_case_4.setText(Combinaison_now.getval_case(3) + "");
    }//GEN-LAST:event_bt_down_4ActionPerformed

    private void bt_up_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_2ActionPerformed
        Combinaison_now.upval_case(1);
        nb_chiffre_case_2.setText(Combinaison_now.getval_case(1) + "");
    }//GEN-LAST:event_bt_up_2ActionPerformed

    private void bt_up_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_3ActionPerformed
        Combinaison_now.upval_case(2);
        nb_chiffre_case_3.setText(Combinaison_now.getval_case(2) + "");
    }//GEN-LAST:event_bt_up_3ActionPerformed

    private void bt_up_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_up_4ActionPerformed
       Combinaison_now.upval_case(3);
        nb_chiffre_case_4.setText(Combinaison_now.getval_case(3) + "");
    }//GEN-LAST:event_bt_up_4ActionPerformed

    private void bt_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_testActionPerformed
        int [] resultat = new int[4];
        resultat = Combinaison_now.tester();
        nb_chiffre_exacts.setText(resultat[0]+"");
        nb_chiffre_trop_hauts.setText(resultat[1]+"");
        nb_chiffre_trop_bas.setText(resultat[2]+"");
        if (resultat[3]==nb_tentative){
            // txt_encouragement.setText("Tu a perdu ");
            nb_score.setText(resultat[3]+" sur "+nb_tentative);
            //Desactivation des touches du a la defaites
            bt_down_1.setEnabled(false);
            bt_down_2.setEnabled(false);
            bt_down_3.setEnabled(false);
            bt_down_4.setEnabled(false);
            
            bt_up_1.setEnabled(false);
            bt_up_2.setEnabled(false);
            bt_up_3.setEnabled(false);
            bt_up_4.setEnabled(false);
            
            bt_test.setEnabled(false);
            Defaite I = new Defaite();
            I.setVisible(true);
            this.dispose();
        }
        if (resultat[0]==4){
            Victoire I = new Victoire();
            I.setVisible(true);
            this.dispose();
            
        }
        else{
           nb_score.setText(resultat[3]+" sur "+nb_tentative); 
        }
        
    }//GEN-LAST:event_bt_testActionPerformed

    private void bt_restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_restartActionPerformed
        Combinaison_now.restart();
        // réinitialise les chiffre a zero
        nb_chiffre_case_1.setText(Combinaison_now.getval_case(0) + "");
        nb_chiffre_case_2.setText(Combinaison_now.getval_case(1) + "");
        nb_chiffre_case_3.setText(Combinaison_now.getval_case(2) + "");
        nb_chiffre_case_4.setText(Combinaison_now.getval_case(3) + "");
        // réinitialise le score
        nb_score.setText(0+" sur 10");
        // réinitialise les valeur obtenu quand test effectuer
        nb_chiffre_exacts.setText(0+"");
        nb_chiffre_trop_hauts.setText(0+"");
        nb_chiffre_trop_bas.setText(0+"");
        
//Reactive le fonctionnement des boutons
        bt_down_1.setEnabled(true);
        bt_down_2.setEnabled(true);
        bt_down_3.setEnabled(true);
        bt_down_4.setEnabled(true);
            
        bt_up_1.setEnabled(true);
        bt_up_2.setEnabled(true);
        bt_up_3.setEnabled(true);
        bt_up_4.setEnabled(true);
            
        bt_test.setEnabled(true);
    }//GEN-LAST:event_bt_restartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface(10).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_down_1;
    private javax.swing.JButton bt_down_2;
    private javax.swing.JButton bt_down_3;
    private javax.swing.JButton bt_down_4;
    private javax.swing.JButton bt_restart;
    private javax.swing.JButton bt_test;
    private javax.swing.JButton bt_up_1;
    private javax.swing.JButton bt_up_2;
    private javax.swing.JButton bt_up_3;
    private javax.swing.JButton bt_up_4;
    private javax.swing.JLabel nb_chiffre_case_1;
    private javax.swing.JLabel nb_chiffre_case_2;
    private javax.swing.JLabel nb_chiffre_case_3;
    private javax.swing.JLabel nb_chiffre_case_4;
    private javax.swing.JLabel nb_chiffre_exacts;
    private javax.swing.JLabel nb_chiffre_trop_bas;
    private javax.swing.JLabel nb_chiffre_trop_hauts;
    private javax.swing.JLabel nb_score;
    private javax.swing.JLabel txt_chiffre_exacts;
    private javax.swing.JLabel txt_chiffre_trop_bas;
    private javax.swing.JLabel txt_chiffre_trop_hauts;
    private javax.swing.JLabel txt_encouragement;
    private javax.swing.JLabel txt_tentative;
    // End of variables declaration//GEN-END:variables
}
