/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emeka
 */
public class Selectiv_nb_tentative extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Selectiv_nb_tentative.class.getName());

    /**
     * Creates new form Selectiv_nb_tentative
     */
    public Selectiv_nb_tentative() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_10_tentatives = new javax.swing.JButton();
        bt_5_tentatives = new javax.swing.JButton();
        bt_20_tentatives = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_10_tentatives.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_10_tentatives.setText("10");
        bt_10_tentatives.setBorder(new javax.swing.border.MatteBorder(null));
        bt_10_tentatives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_10_tentativesActionPerformed(evt);
            }
        });

        bt_5_tentatives.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_5_tentatives.setText("5");
        bt_5_tentatives.setBorder(new javax.swing.border.MatteBorder(null));
        bt_5_tentatives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5_tentativesActionPerformed(evt);
            }
        });

        bt_20_tentatives.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_20_tentatives.setText("20");
        bt_20_tentatives.setBorder(new javax.swing.border.MatteBorder(null));
        bt_20_tentatives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_20_tentativesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selectionner le nombre de tentative max");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_20_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_5_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_10_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(144, 144, 144))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_5_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_10_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_20_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_10_tentativesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_10_tentativesActionPerformed
        Interface I = new Interface(10);
        I.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_10_tentativesActionPerformed

    private void bt_5_tentativesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5_tentativesActionPerformed
        Interface I = new Interface(5);
        I.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_5_tentativesActionPerformed

    private void bt_20_tentativesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_20_tentativesActionPerformed
        Interface I = new Interface(20);
        I.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_20_tentativesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Selectiv_nb_tentative().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_10_tentatives;
    private javax.swing.JButton bt_20_tentatives;
    private javax.swing.JButton bt_5_tentatives;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
